[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#4b5563"
textColor = "#f8fafc"

[server]
headless = true
port = 8503
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 50
